version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x

  build:
    commands:
      - npm install
      - npm run-script build

artifacts:
  base-directory: build
  files:
    - "**/*"
